/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class group_gnometrading_networking_sockets_NativeSocket */

#ifndef _Included_group_gnometrading_networking_sockets_NativeSocket
#define _Included_group_gnometrading_networking_sockets_NativeSocket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     group_gnometrading_networking_sockets_NativeSocket
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_group_gnometrading_networking_sockets_NativeSocket_init
  (JNIEnv *, jclass);

/*
 * Class:     group_gnometrading_networking_sockets_NativeSocket
 * Method:    socket
 * Signature: (ZZ)I
 */
JNIEXPORT jint JNICALL Java_group_gnometrading_networking_sockets_NativeSocket_socket
  (JNIEnv *, jobject, jboolean, jboolean);

/*
 * Class:     group_gnometrading_networking_sockets_NativeSocket
 * Method:    connect0
 * Signature: (ILjava/net/InetAddress;I)I
 */
JNIEXPORT jint JNICALL Java_group_gnometrading_networking_sockets_NativeSocket_connect0
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     group_gnometrading_networking_sockets_NativeSocket
 * Method:    close0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_group_gnometrading_networking_sockets_NativeSocket_close0
  (JNIEnv *, jobject, jint);

/*
 * Class:     group_gnometrading_networking_sockets_NativeSocket
 * Method:    read0
 * Signature: (IJII)I
 */
JNIEXPORT jint JNICALL Java_group_gnometrading_networking_sockets_NativeSocket_read0
  (JNIEnv *, jobject, jint, jlong, jint, jint);

/*
 * Class:     group_gnometrading_networking_sockets_NativeSocket
 * Method:    write0
 * Signature: (IJII)I
 */
JNIEXPORT jint JNICALL Java_group_gnometrading_networking_sockets_NativeSocket_write0
  (JNIEnv *, jobject, jint, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
