/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class group_gnometrading_networking_sockets_NativeSSLSocket */

#ifndef _Included_group_gnometrading_networking_sockets_NativeSSLSocket
#define _Included_group_gnometrading_networking_sockets_NativeSSLSocket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     group_gnometrading_networking_sockets_NativeSSLSocket
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_group_gnometrading_networking_sockets_NativeSSLSocket_init
  (JNIEnv *, jclass);

/*
 * Class:     group_gnometrading_networking_sockets_NativeSSLSocket
 * Method:    socket
 * Signature: (ZZ)J
 */
JNIEXPORT jlong JNICALL Java_group_gnometrading_networking_sockets_NativeSSLSocket_socket
  (JNIEnv *, jobject, jboolean, jboolean);

/*
 * Class:     group_gnometrading_networking_sockets_NativeSSLSocket
 * Method:    connect0
 * Signature: (JLjava/net/InetAddress;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_group_gnometrading_networking_sockets_NativeSSLSocket_connect0
  (JNIEnv *, jobject, jlong, jobject, jint, jstring);

/*
 * Class:     group_gnometrading_networking_sockets_NativeSSLSocket
 * Method:    close0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_group_gnometrading_networking_sockets_NativeSSLSocket_close0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     group_gnometrading_networking_sockets_NativeSSLSocket
 * Method:    read0
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_group_gnometrading_networking_sockets_NativeSSLSocket_read0
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     group_gnometrading_networking_sockets_NativeSSLSocket
 * Method:    write0
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_group_gnometrading_networking_sockets_NativeSSLSocket_write0
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     group_gnometrading_networking_sockets_NativeSSLSocket
 * Method:    configureBlocking0
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_group_gnometrading_networking_sockets_NativeSSLSocket_configureBlocking0
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     group_gnometrading_networking_sockets_NativeSSLSocket
 * Method:    setKeepAlive0
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_group_gnometrading_networking_sockets_NativeSSLSocket_setKeepAlive0
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     group_gnometrading_networking_sockets_NativeSSLSocket
 * Method:    setReceiveBufferSize0
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_group_gnometrading_networking_sockets_NativeSSLSocket_setReceiveBufferSize0
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     group_gnometrading_networking_sockets_NativeSSLSocket
 * Method:    setSendBufferSize0
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_group_gnometrading_networking_sockets_NativeSSLSocket_setSendBufferSize0
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     group_gnometrading_networking_sockets_NativeSSLSocket
 * Method:    setTcpNoDelay0
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_group_gnometrading_networking_sockets_NativeSSLSocket_setTcpNoDelay0
  (JNIEnv *, jobject, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
