name: Build and Deploy Maven Jars
on:
  push:
    branches:
      - 'master'
      - 'main'

jobs:
  deploy-os-specific-jars:
    runs-on: ${{ matrix.os.os }}
    permissions:
      packages: write
    strategy:
      matrix:
        os: [{os: ubuntu-latest, classifier: linux}, {os: macos-latest, classifier: macos}]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Zulu 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml

      - name: Build OS-Specific JAR
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn clean package

      - name: Deploy OS-Specific JAR
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn deploy:deploy-file \
            -Dfile=target/gnome-networking-${{ matrix.os.classifier }}.jar \
            -DgroupId=group.gnometrading \
            -DartifactId=gnome-networking \
            -Dversion=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) \
            -Dclassifier=${{ matrix.os.classifier }} \
            -DgeneratePom=false \
            -Dpackaging=jar \
            -DrepositoryId=github \
            -Durl=https://maven.pkg.github.com/gnome-trading-group/gnome-networking \
            --settings settings.xml \
          || { echo "Ignoring 409 Conflict errors..." }
